config/routes.rb
#                                          PATCH    /admin/products/categories/:id(.:format)                                                          admin/categories#update
#                                          PUT      /admin/products/categories/:id(.:format)                                                          admin/categories#update
#                                          DELETE   /admin/products/categories/:id(.:format)                                                          admin/categories#destroy
#                            admin_options GET      /admin/products/options(.:format)                                                                 admin/options#index
#                           admin_products GET      /admin/products(.:format)                                                                         admin/products#index
#                                          POST     /admin/products(.:format)                                                                         admin/products#create
#                        new_admin_product GET      /admin/products/new(.:format)                                                                     admin/products#new
#                       edit_admin_product GET      /admin/products/:id/edit(.:format)                                                                admin/products#edit
#                            admin_product GET      /admin/products/:id(.:format)                                                                     admin/products#show
#                                          PATCH    /admin/products/:id(.:format)                                                                     admin/products#update
#                                          PUT      /admin/products/:id(.:format)                                                                     admin/products#update
#                                          DELETE   /admin/products/:id(.:format)                                                                     admin/products#destroy
#                                     root GET      /                                                                                                 home#index
#                                 products GET      /products(.:format)                                                                               products#index
#                                  product GET      /products/:id(.:format)                                                                           products#show
#                          cities_pilipina GET      /pilipinas/:name/cities(.:format)                                                                 pilipinas#cities
#                       barangays_pilipina GET      /pilipinas/:name/barangays(.:format)                                                              pilipinas#barangays
#                shipping_details_checkout POST     /checkout/:id/shipping_details(.:format)                                                          checkouts#shipping_details
#                  payment_method_checkout POST     /checkout/:id/payment_method(.:format)                                                            checkouts#payment_method
#                                 checkout GET      /checkout/:id(.:format)                                                                           checkouts#show
#                              total_carts GET      /carts/total(.:format)                                                                            carts#total
#                              count_carts GET      /carts/count(.:format)                                                                            carts#count
#                           sync_all_carts POST     /carts/sync_all(.:format)                                                                         carts#sync_all
#                   proceed_checkout_carts POST     /carts/proceed_checkout(.:format)                                                                 carts#proceed_checkout
#                        bulk_delete_carts DELETE   /carts/bulk_delete(.:format)                                                                      carts#bulk_delete
#                    variant_dropdown_cart GET      /carts/:id/variant_dropdown(.:format)                                                             carts#variant_dropdown
#                                sync_cart POST     /carts/:id/sync(.:format)                                                                         carts#sync
#                                    carts GET      /carts(.:format)                                                                                  carts#index
#                                     cart PATCH    /carts/:id(.:format)                                                                              carts#update
#                                          PUT      /carts/:id(.:format)                                                                              carts#update
#                                          DELETE   /carts/:id(.:format)                                                                              carts#destroy
#                             info_variant GET      /variants/:id/info(.:format)                                                                      variants#info
#                      add_to_cart_variant POST     /variants/:id/add_to_cart(.:format)                                                               variants#add_to_cart
#                guest_add_to_cart_variant POST     /variants/:id/guest_add_to_cart(.:format)                                                         variants#guest_add_to_cart
#                          buy_now_variant POST     /variants/:id/buy_now(.:format)                                                                   variants#buy_now
#                    guest_buy_now_variant POST     /variants/:id/guest_buy_now(.:format)                                                             variants#guest_buy_now
#                                  account GET      /account(.:format)                                                                                accounts#show
#                               sync_order POST     /orders/:id/sync(.:format)                                                                        orders#sync
#                             cancel_order DELETE   /orders/:id/cancel(.:format)                                                                      orders#cancel
#                                   orders GET      /orders(.:format)                                                                                 orders#index
#                                    order GET      /orders/:id(.:format)                                                                             orders#show
#                                                   /404(.:format)                                                                                    errors#not_found
#                                                   /500(.:format)                                                                                    errors#internal_server_error
#         turbo_recede_historical_location GET      /recede_historical_location(.:format)                                                             turbo/native/navigation#recede
#         turbo_resume_historical_location GET      /resume_historical_location(.:format)                                                             turbo/native/navigation#resume
#        turbo_refresh_historical_location GET      /refresh_historical_location(.:format)                                                            turbo/native/navigation#refresh
#            rails_postmark_inbound_emails POST     /rails/action_mailbox/postmark/inbound_emails(.:format)                                           action_mailbox/ingresses/postmark/inbound_emails#create
#               rails_relay_inbound_emails POST     /rails/action_mailbox/relay/inbound_emails(.:format)                                              action_mailbox/ingresses/relay/inbound_emails#create
#            rails_sendgrid_inbound_emails POST     /rails/action_mailbox/sendgrid/inbound_emails(.:format)                                           action_mailbox/ingresses/sendgrid/inbound_emails#create
#      rails_mandrill_inbound_health_check GET      /rails/action_mailbox/mandrill/inbound_emails(.:format)                                           action_mailbox/ingresses/mandrill/inbound_emails#health_check
#            rails_mandrill_inbound_emails POST     /rails/action_mailbox/mandrill/inbound_emails(.:format)                                           action_mailbox/ingresses/mandrill/inbound_emails#create
#             rails_mailgun_inbound_emails POST     /rails/action_mailbox/mailgun/inbound_emails/mime(.:format)                                       action_mailbox/ingresses/mailgun/inbound_emails#create
#           rails_conductor_inbound_emails GET      /rails/conductor/action_mailbox/inbound_emails(.:format)                                          rails/conductor/action_mailbox/inbound_emails#index
#                                          POST     /rails/conductor/action_mailbox/inbound_emails(.:format)                                          rails/conductor/action_mailbox/inbound_emails#create
#        new_rails_conductor_inbound_email GET      /rails/conductor/action_mailbox/inbound_emails/new(.:format)                                      rails/conductor/action_mailbox/inbound_emails#new
#            rails_conductor_inbound_email GET      /rails/conductor/action_mailbox/inbound_emails/:id(.:format)                                      rails/conductor/action_mailbox/inbound_emails#show

app/models/product.rb
# frozen_string_literal: true

class Product < ApplicationRecord
  # Constants
  MAX_IMAGES = 10
  ALLOWED_IMAGE_TYPES = %w[image/png image/jpg image/jpeg].freeze

  # Attachments & Rich text
  has_rich_text :description

  has_many_attached :images do |attachable|
    attachable.variant :small, resize_to_limit: [100, 100]
    attachable.variant :thumb, resize_to_limit: [320, 320]
  end
  has_one_attached :thumbnail do |attachable|
    attachable.variant :small, resize_to_limit: [100, 100]
    attachable.variant :card, resize_to_limit: [320, 320]
  end

  # Relations
  has_one :seo, dependent: :destroy

  has_many :variants, dependent: :destroy
  has_many :product_options, dependent: :destroy
  has_many :options, through: :product_options, dependent: :destroy
  has_many :product_categories, dependent: :destroy
  has_many :categories, through: :product_categories, dependent: :destroy

  # Scoped relations
  has_one :master_variant, lambda {
    where(is_master: true)
  }, class_name: 'Variant', inverse_of: :product, dependent: :destroy

  # Nested form
  accepts_nested_attributes_for :master_variant, :seo

  # Scopes
  scope :sort_by_latest, -> { order(created_at: :desc) }
  scope :base_on_date, lambda { |today = Date.current|
    where(available_on: ..today)
      .where('discontinue_on IS NULL OR discontinue_on > ?', today)
  }

  # Validations
  validates :name, :master_variant, :currency, presence: true
  validates :discount_percent, numericality: { greater_than_or_equal_to: 0, less_than_or_equal_to: 100 }
  validates :review_avg_rating, numericality: { in: 0..5 }
  validates :lowest_price, numericality: { greater_than_or_equal_to: 0 }, allow_nil: true
  validates :highest_price, numericality: { greater_than_or_equal_to: 0 }, allow_nil: true
  validates :thumbnail, content_type: ALLOWED_IMAGE_TYPES
  validates :images, content_type: ALLOWED_IMAGE_TYPES,
                     limit: { max: MAX_IMAGES, message: I18n.t('images.validate.max', max: MAX_IMAGES) }
end

# == Schema Information
#
# Table name: products
#
#  id                :uuid             not null, primary key
#  available_on      :date
#  currency          :string           default("PHP"), not null
#  discontinue_on    :date
#  discount_percent  :integer          default(0), not null
#  has_variant       :boolean          default(FALSE), not null
#  highest_price     :decimal(10, 2)
#  lowest_price      :decimal(10, 2)
#  name              :string           not null
#  order_must_login  :boolean          default(FALSE), not null
#  promotable        :boolean          default(TRUE), not null
#  review_avg_rating :decimal(1, 1)    default(0.0)
#  review_count      :integer          default(0)
#  created_at        :datetime         not null
#  updated_at        :datetime         not null
#
# Indexes
#
#  index_products_on_available_on    (available_on)
#  index_products_on_discontinue_on  (discontinue_on)
#  index_products_on_highest_price   (highest_price)
#  index_products_on_lowest_price    (lowest_price)
#  index_products_on_name            (name)
#

app/controllers/carts_controller.rb
# frozen_string_literal: true

class CartsController < BaseController
  load_and_authorize_resource

  def index
    @carts = Cart.detailed.accessible_by(current_ability)
    return if params[:bn].blank?

    @carts = @carts.sort_by { |cart| cart.id == params[:bn] ? 0 : 1 }
  end

  def update
    respond_to do |format|
      if @cart.update(cart_params)
        format.turbo_stream
      else
        format.turbo_stream { render :error, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @cart.destroy
  end

  def sync
    respond_to do |format|
      if (@common_cart = current_user.carts.find_by(variant_id: @cart.variant_id)).present?
        ActiveRecord::Base.transaction do
          @common_cart.update(qty: @cart.qty + @common_cart.qty)
          @cart.destroy
        rescue ActiveRecord::RecordInvalid
          format.turbo_stream { render :error, :unprocessable_entity }
        else
          format.turbo_stream { render :sync_common }
        end
      elsif @cart.update(user: current_user, guest_session: nil)
        format.turbo_stream
      else
        format.turbo_stream { render :error, :unprocessable_entity }
      end
    end
  end

  def sync_all; end

  def variant_dropdown; end

  def proceed_checkout
    @carts = @carts.accessible_by(current_ability, :proceed_checkout)
    @carts = @carts.where(id: params[:ids]) if params[:ids].present?

    if @carts.count.positive? && (order = Cart.checkout(@carts, user: current_user, guest_session:)).present?
      redirect_to checkout_url(order), notice: I18n.t('checkouts.created')
    else
      redirect_to carts_path, alert: I18n.t('error.something_went_wrong')
    end
  end

  def total
    @carts = Cart.accessible_by(current_ability, :total)
    @carts = @carts.where(id: params[:ids]) if params[:ids].present?
    @total = @carts.variants_total
  end

  def bulk_delete
    @carts = Cart.accessible_by(current_ability, :bulk_delete)
    @carts = @carts.where(id: params[:ids]) if params[:ids].present?
    @carts = @carts.destroy_all
  end

  def count
    @carts = Cart.joins(:variant).accessible_by(current_ability, :count)
    @cart_count = @carts.count
    cookies.signed[:cart_count] = @cart_count
  end

  private

  def cart_params
    params.require(:cart).permit(:qty, :variant_id)
  end
end

app/helpers/carts_helper.rb
# frozen_string_literal: true
# typed: true

module CartsHelper
  extend T::Sig

  sig { params(count_on_hand: Integer, qty: Integer, sale: T::Boolean).returns(T::Boolean) }
  def checkbox_invalid?(count_on_hand, qty, sale)
    (!sale && count_on_hand.zero?) || quantity_invalid?(count_on_hand, qty, sale)
  end

  sig { params(count_on_hand: Integer, qty: Integer, sale: T::Boolean).returns(T::Boolean) }
  def quantity_invalid?(count_on_hand, qty, sale)
    !sale && count_on_hand < qty
  end
end

app/views/carts/_item_details.html.haml
.flex.w-full.gap-3.col-span-3.items-center.pl-5
  .flex.gap-3.items-center{class: "w-[65%]"}
    = render "item_checkbox", cart:
    .flex.gap-2
      = link_to product_path(cart.product_slug, pid: cart.product_uuid) do
        = image_tag cart.variant_thumbnail || cart.product_thumbnail || "thumbnail.png", size: 320, class: "min-w-[75px] min-h-[75px] max-w-[75px] max-h-[75px] object-cover object-center border rounded-sm", id: "cart-#{cart.uuid}-thumbnail"
      .flex.flex-col.gap-1
        = link_to product_path(cart.product_slug, pid: cart.product_uuid), class: "leading-tight line-clamp-2 text-[15px]" do
          = cart.product_name
        - if cart.user_id.blank? && cart.guest_session_id.present?
          .flex.items-center{id: "cart-#{cart.uuid}-guest-display", class: "gap-2.5"}
            %div{data: {controller: "popover"}}
              .relative.cursor-help{data: {action: "mouseenter->popover#show mouseleave->popover#hide"}}
                = render TagComponent.new variant: :warning do
                  Guest
              %template{data: {"popover-target": "content"}}
                .popover{data: {"popover-target": "card"}}
                  .w-60.py-2.px-3.text-sm.text-gray-600
                    This is a guest cart saved in this browser, 
                    = icon("fa-solid", "arrows-rotate", class: "text-gray-700")
                    sync this card to own the cart.
            - if can?(:sync, cart)
              = button_to sync_cart_path(cart.uuid), method: :post do
                = icon("fa-solid", "arrows-rotate", class: "text-gray-400 text-lg hover:text-gray-600")
  - unless cart.is_master
    %button.flex.flex-col.text-zinc-500.items-center{id: "cart-#{cart.uuid}-variant-pair"}
      .flex.gap-2.items-center
        Variations:
        = icon("fa-solid", "caret-down")
      #variant-pair
        = cart.variant_pair

app/views/carts/bulk_delete.turbo_stream.haml
= turbo_stream.prepend "notification-container" do
  = render NotificationComponent.new notif_type: "success", message: t("carts.destroyed")

- @carts.each do |cart|
  = turbo_stream.remove "cart-#{cart.id}"

= turbo_stream.replace "cart-count" do
  = render "layouts/cart_count_frame", count: cookies.signed[:cart_count] || 0

app/views/carts/destroy.turbo_stream.haml
= turbo_stream.prepend "notification-container" do
  = render NotificationComponent.new notif_type: "success", message: I18n.t('carts.destroyed')

= turbo_stream.remove "cart-#{@cart.id}"

= turbo_stream.replace "cart-count" do
  = render "layouts/cart_count_frame", count: cookies.signed[:cart_count] || 0

app/views/carts/error.turbo_stream.haml
= turbo_stream.prepend "notification-container" do
  = render NotificationComponent.new notif_type: "error", message: t("carts.something_went_wrong")

app/views/carts/index.html.haml
- title "Carts"
- description "Manage your carts."
- keywords "cart, product, checkout, buy now"

.w-full.margin-max-screen.py-7
  .relative.grid{data: {controller: "carts--select-all items", proceed_checkout_url: proceed_checkout_carts_path, total_url: total_carts_path, bulk_delete_url: bulk_delete_carts_path, empty: "items-empty", "item": "cart-item"}}
    .grid
      .grid.gap-3.grid-cols-7.py-4.place-items-center.border
        .col-span-3.w-full.flex.gap-3.items-center.pl-5
          = check_box_tag "select-all", "yes", false, id: "checkbox-all", data: {"carts--select-all-target": "checkboxAll"}, class: "checkbox-primary"
          %label.font-semibold.text-primary.cursor-pointer{for: "checkbox-all"}
            = t("carts.table.thead.product")
        .block
          = t("carts.table.thead.unit_price")
        .block
          = t("carts.table.thead.quantity")
        .block
          = t("carts.table.thead.subtotal")
        .block
          = t("carts.table.thead.actions")
      .border-x.divide-y
        - if @carts.present?
          - @carts.each do |cart|
            = render Carts::Item::BaseComponent.new cart:
        = render EmptyItemComponent.new text: "No carts yet", hide: @carts.present?
    .grid.sticky.bottom-0.w-full.bg-white.border
      .flex.py-4.px-5.justify-between.gap-5.w-full
        .flex.gap-6.items-center
          .flex.gap-3.items-center
            = check_box_tag "select-all", "yes", false, id: "select-all", data: {"carts--select-all-target": "selectAll", action: "carts--select-all#selectAllToggle"}, class: "checkbox-primary"
            %label.cursor-pointer{for: "select-all", data: {"carts--select-all-target": "activeCount"}}
              = "Select All (#{@carts.size})"
          %button.hover:text-red-600.disabled:text-gray-400.disabled:cursor-not-allowed{disabled: true, data: {action: "carts--select-all#bulkDelete", "carts--select-all-target": "bulkDeleteBtn"}}
            Delete
        .flex.gap-3.items-center
          .flex.items-center.gap-2
            .block{data: {"carts--select-all-target": "selected"}}
              Total (0 item)
            #carts-total{data: {"carts--select-all-target": "total"}}
              = render PriceRangeComponent.new lowest: 0, currency: MoneyRails.default_currency.id.to_s
          %button.btn-primary.disabled:bg-gray-300.disabled:cursor-not-allowed.px-14{disabled: true, data: {"carts--select-all-target": "checkoutBtn", action: "carts--select-all#proceedCheckout"}}
            Checkout

app/views/carts/item_update.turbo_stream.haml
- if @cart.qty_previously_changed?
  = turbo_stream.replace "cart-#{@cart.uuid}-total-price" do
    = render "item_total_price", cart: @cart
  = turbo_stream.replace "cart-#{@cart.uuid}-unit-price" do
    = render "item_unit_price", cart: @cart

app/views/carts/proceed_checkout.turbo_stream.haml
- unless @carts.count.positive?
  = turbo_stream.prepend "notification-container" do
    = render NotificationComponent.new notif_type: "error", message: t("carts.no_carts_found")

app/views/carts/sync.turbo_stream.haml
= turbo_stream.prepend "notification-container" do
  = render NotificationComponent.new notif_type: "success", message: t("carts.synced")

= turbo_stream.remove "cart-#{@cart.id}-guest-display"

- unless @cart.variant.is_master
  = turbo_stream.replace "cart-#{@cart.id}-dropdown-variant-pair" do
    = render Carts::Item::VariantButtonComponent.new cart: @cart, variant_pair: @cart.variant.option_value_name, count_on_hand: @cart.variant.count_on_hand, sale: sale?(@cart.variant)

= turbo_stream.replace "cart-#{@cart.id}-qty" do
  = render Carts::Item::QtyComponent.new cart: @cart, count_on_hand: @cart.variant.count_on_hand, sale: sale?(@cart.variant)

= turbo_stream.replace "cart-#{@cart.id}-checkbox" do
  = render Carts::Item::CheckboxComponent.new cart: @cart, invalid: cannot?(:proceed_checkout, @cart)

= turbo_stream.replace "cart-count" do
  = render "layouts/cart_count_frame", count: cookies.signed[:cart_count] || 0

app/views/carts/sync_cart.turbo_stream.haml
= turbo_stream.replace "cart-#{@cart.uuid}-checkbox" do
  = render "item_checkbox", cart: @cart

= turbo_stream.remove "cart-#{@cart.uuid}-guest-display"

= turbo.replace "cart-#{cart.uuid}-update-url" do
  = render "item_update_url", cart: @cart

app/views/carts/sync_common.turbo_stream.haml
= turbo_stream.prepend "notification-container" do
  = render NotificationComponent.new notif_type: "success", message: t("carts.synced")

= turbo_stream.remove "cart-#{@cart.id}"

= turbo_stream.replace "cart-#{@common_cart.id}-total-price" do
  = render Carts::Item::TotalpriceComponent.new cart: @common_cart, price: @common_cart.variant.price, currency: @common_cart.variant.product.currency, discount: variant.product.discount_percent

= turbo_stream.replace "cart-#{@common_cart.id}-unit-price" do
  = render Carts::Item::UnitpriceComponent.new cart: @common_cart, price: @common_cart.variant.price, currency: @common_cart.variant.product.currency, discount: variant.product.discount_percent

= turbo_stream.replace "cart-#{@common_cart.id}-qty" do
  = render Carts::Item::QtyComponent.new cart: @common_cart, count_on_hand: @common_cart.variant.count_on_hand, sale: sale?(@common_cart.variant)

= turbo_stream.replace "cart-#{@common_cart.id}-checkbox" do
  = render Carts::Item::CheckboxComponent.new cart: @common_cart, invalid: cannot?(:proceed_checkout, @common_cart)

app/views/carts/total.turbo_stream.haml
= turbo_stream.replace "carts-total" do
  #carts-total{data: {"carts--select-all-target": "total"}}
    = render PriceRangeComponent.new lowest: @total, currency: MoneyRails.default_currency.id.to_s

app/views/carts/update.turbo_stream.haml
- if @cart.qty_previously_changed?
  = turbo_stream.replace "cart-#{@cart.id}-total-price" do
    = render Carts::Item::TotalpriceComponent.new cart: @cart, price: @cart.variant.price, currency: @cart.variant.product.currency, discount: @cart.variant.product.discount_percent

  = turbo_stream.replace "cart-#{@cart.id}-unit-price" do
    = render Carts::Item::UnitpriceComponent.new cart: @cart, price: @cart.variant.price, currency: @cart.variant.product.currency, discount: @cart.variant.product.discount_percent

- if !@cart.variant.is_master && @cart.variant_changed?
  = turbo_stream.replace "cart-#{@cart.id}-dropdown-variant-pair" do
    = render Carts::Item::VariantButtonComponent.new cart: @cart, variant_pair: @cart.variant.option_value_name, count_on_hand: @cart.variant.count_on_hand, sale: sale?(@cart.variant)

= turbo_stream.replace "cart-#{@cart.id}-checkbox" do
  = render Carts::Item::CheckboxComponent.new cart: @cart, invalid: cannot?(:proceed_checkout, @cart), checked: ActiveModel::Type::Boolean.new.cast(params[:checked])

= turbo_stream.replace "cart-#{@cart.id}-qty" do
  = render Carts::Item::QtyComponent.new cart: @cart, count_on_hand: @cart.variant.count_on_hand, sale: sale?(@cart.variant)

app/views/carts/variant_dropdown.html.haml
= turbo_frame_tag "variant-#{@cart.id}-dropdown" do
  .grid.gap-4{data: {"controller": "carts--dropdown"}}
    .flex.flex-col.gap-4
      #current-variant.hidden{data: {"carts--dropdown-target": "currentVariant", value: @cart.variant.id, cart: @cart.id}}
      - @cart.variant.product.product_options.with_option_columns.each do |po|
        .flex.flex-col.gap-3{data: {"carts--dropdown-target": "optionInstance"}}
          %span.font-medium.text-sm.text-zinc-500
            = po.display_name
          .flex.flex-wrap{class: "gap-2.5", data: {"carts--dropdown-target": "option"}}
            - po.variant_option_values.with_variant_position.group_by { |h| h.name }.each do |vname, arr|
              - is_active = arr.any? { |a| a.variant_id == @cart.variant_id }
              .flex
                = radio_button_tag po.name, vname, is_active, id: "#{vname}-#{@cart.id}", class: "peer hidden", data: {action: "click->carts--dropdown#radioToggle", was_checked: is_active, variant_ids: arr.map { |a| a.variant_id }.join(','), "carts--dropdown-target": "radio"}
                %label.variant-radio.py-2{for: "#{vname}-#{@cart.id}"}
                  = vname
    = render StockCountComponent.new count: @cart.variant.count_on_hand, sale: sale?(@cart.variant)
    .flex.gap-2.-mt-1
      %button.btn-plain.py-2{class: "w-1/2", data: {action: "dropdown#toggle"}}
        Cancel
      %button.btn-primary.py-2{class: "w-1/2"}
        Update

app/views/carts/variant_dropdown.turbo_stream.haml
= turbo_stream.replace "variant-dropdown-#{@cart.uuid}" do
  .flex.flex-col.gap-5.mb-3{data: {"controller": "carts--dropdown"}}
    #current-variant.hidden{data: {"carts--dropdown-target": "currentVariant", value: @cart.variant.uuid, cart: @cart.uuid}}
    - @cart.variant.product.product_options.with_option_columns.each do |po|
      .flex.flex-col.gap-3{data: {"carts--dropdown-target": "optionInstance"}}
        %span.font-medium.text-sm.text-zinc-500
          = po.display_name
        %ul.flex-wrap.flex{class: "gap-2.5", data: {"carts--dropdown-target": "option"}}
          - po.variant_option_values.with_variant_position.group_by { |h| h.name }.each do |vname, arr|
            - is_active = arr.any? { |a| a.variant_id == @cart.variant_id }
            %li
              = radio_button_tag po.name, vname, is_active, id: "#{vname}-#{@cart.uuid}",
              class: "peer hidden", disabled: true, data: {action: "click->carts--dropdown#radioToggle", 
              was_checked: is_active, variant_ids: arr.map { |a| a.variant_uuid }.join(','),
              "carts--dropdown-target": "radio"}
              %label.variant-radio{for: "#{vname}-#{@cart.uuid}"}
                = vname