config/routes.rb
#                                          DELETE   /auth(.:format)                                                                                   registrations#destroy
#                                          POST     /auth(.:format)                                                                                   registrations#create
#                                    admin GET      /admin(.:format)                                                                                  redirect(301, /admin/dashboard)
#                    admin_dashboard_index GET      /admin/dashboard(.:format)                                                                        admin/dashboard#index
#                              admin_users GET      /admin/users(.:format)                                                                            admin/users#index
#                         ship_admin_order POST     /admin/orders/:id/ship(.:format)                                                                  admin/orders#ship
#                      recieve_admin_order POST     /admin/orders/:id/recieve(.:format)                                                               admin/orders#recieve
#                     complete_admin_order POST     /admin/orders/:id/complete(.:format)                                                              admin/orders#complete
#                       return_admin_order POST     /admin/orders/:id/return(.:format)                                                                admin/orders#return
#                       refund_admin_order POST     /admin/orders/:id/refund(.:format)                                                                admin/orders#refund
#      update_shipping_details_admin_order PATCH    /admin/orders/:id/update_shipping_details(.:format)                                               admin/orders#update_shipping_details
#      update_logistic_details_admin_order PATCH    /admin/orders/:id/update_logistic_details(.:format)                                               admin/orders#update_logistic_details
#         update_return_reason_admin_order PATCH    /admin/orders/:id/update_return_reason(.:format)                                                  admin/orders#update_return_reason
#         update_refund_reason_admin_order PATCH    /admin/orders/:id/update_refund_reason(.:format)                                                  admin/orders#update_refund_reason
#         update_internal_note_admin_order PATCH    /admin/orders/:id/update_internal_note(.:format)                                                  admin/orders#update_internal_note
#                       cancel_admin_order DELETE   /admin/orders/:id/cancel(.:format)                                                                admin/orders#cancel
#                             admin_orders GET      /admin/orders(.:format)                                                                           admin/orders#index
#                              admin_order GET      /admin/orders/:id(.:format)                                                                       admin/orders#show
#                                          DELETE   /admin/orders/:id(.:format)                                                                       admin/orders#destroy
#           position_admin_product_variant PATCH    /admin/products/:product_id/variants/:id/position(.:format)                                       admin/products/variants#position
#                   admin_product_variants GET      /admin/products/:product_id/variants(.:format)                                                    admin/products/variants#index
#                                          POST     /admin/products/:product_id/variants(.:format)                                                    admin/products/variants#create
#                new_admin_product_variant GET      /admin/products/:product_id/variants/new(.:format)                                                admin/products/variants#new
#                    admin_product_variant GET      /admin/products/:product_id/variants/:id(.:format)                                                admin/products/variants#show
#                                          PATCH    /admin/products/:product_id/variants/:id(.:format)                                                admin/products/variants#update
#                                          PUT      /admin/products/:product_id/variants/:id(.:format)                                                admin/products/variants#update
#                                          DELETE   /admin/products/:product_id/variants/:id(.:format)                                                admin/products/variants#destroy
#               modify_admin_product_stock PUT      /admin/products/:product_id/stocks/:id/modify(.:format)                                           admin/products/stocks#modify
#                     admin_product_stocks GET      /admin/products/:product_id/stocks(.:format)                                                      admin/products/stocks#index
#                      admin_product_stock PATCH    /admin/products/:product_id/stocks/:id(.:format)                                                  admin/products/stocks#update
#                                          PUT      /admin/products/:product_id/stocks/:id(.:format)                                                  admin/products/stocks#update
#              upload_admin_product_images POST     /admin/products/:product_id/images/upload(.:format)                                               admin/products/images#upload
#             position_admin_product_image PATCH    /admin/products/:product_id/images/:id/position(.:format)                                         admin/products/images#position
#                     admin_product_images GET      /admin/products/:product_id/images(.:format)                                                      admin/products/images#index
#                                          POST     /admin/products/:product_id/images(.:format)                                                      admin/products/images#create
#                      admin_product_image GET      /admin/products/:product_id/images/:id(.:format)                                                  admin/products/images#show
#                                          PATCH    /admin/products/:product_id/images/:id(.:format)                                                  admin/products/images#update
#                                          PUT      /admin/products/:product_id/images/:id(.:format)                                                  admin/products/images#update
#                                          DELETE   /admin/products/:product_id/images/:id(.:format)                                                  admin/products/images#destroy
#                         admin_categories GET      /admin/products/categories(.:format)                                                              admin/categories#index
#                                          POST     /admin/products/categories(.:format)                                                              admin/categories#create
#                       new_admin_category GET      /admin/products/categories/new(.:format)                                                          admin/categories#new
#                      edit_admin_category GET      /admin/products/categories/:id/edit(.:format)                                                     admin/categories#edit
#                           admin_category GET      /admin/products/categories/:id(.:format)                                                          admin/categories#show
#                                          PATCH    /admin/products/categories/:id(.:format)                                                          admin/categories#update
#                                          PUT      /admin/products/categories/:id(.:format)                                                          admin/categories#update
#                                          DELETE   /admin/products/categories/:id(.:format)                                                          admin/categories#destroy
#                            admin_options GET      /admin/products/options(.:format)                                                                 admin/options#index
#                           admin_products GET      /admin/products(.:format)                                                                         admin/products#index
#                                          POST     /admin/products(.:format)                                                                         admin/products#create
#                        new_admin_product GET      /admin/products/new(.:format)                                                                     admin/products#new
#                       edit_admin_product GET      /admin/products/:id/edit(.:format)                                                                admin/products#edit
#                            admin_product GET      /admin/products/:id(.:format)                                                                     admin/products#show
#                                          PATCH    /admin/products/:id(.:format)                                                                     admin/products#update
#                                          PUT      /admin/products/:id(.:format)                                                                     admin/products#update
#                                          DELETE   /admin/products/:id(.:format)                                                                     admin/products#destroy
#                                     root GET      /                                                                                                 home#index

app/models/product.rb
# frozen_string_literal: true

class Product < ApplicationRecord
  # Constants
  MAX_IMAGES = 10
  ALLOWED_IMAGE_TYPES = %w[image/png image/jpg image/jpeg].freeze

  # Attachments & Rich text
  has_rich_text :description

  has_many_attached :images do |attachable|
    attachable.variant :small, resize_to_limit: [100, 100]
    attachable.variant :thumb, resize_to_limit: [320, 320]
  end
  has_one_attached :thumbnail do |attachable|
    attachable.variant :small, resize_to_limit: [100, 100]
    attachable.variant :card, resize_to_limit: [320, 320]
  end

  # Relations
  has_one :seo, dependent: :destroy

  has_many :variants, dependent: :destroy
  has_many :product_options, dependent: :destroy
  has_many :options, through: :product_options, dependent: :destroy
  has_many :product_categories, dependent: :destroy
  has_many :categories, through: :product_categories, dependent: :destroy

  # Scoped relations
  has_one :master_variant, lambda {
    where(is_master: true)
  }, class_name: 'Variant', inverse_of: :product, dependent: :destroy

  # Nested form
  accepts_nested_attributes_for :master_variant, :seo

  # Scopes
  scope :sort_by_latest, -> { order(created_at: :desc) }
  scope :base_on_date, lambda { |today = Date.current|
    where(available_on: ..today)
      .where('discontinue_on IS NULL OR discontinue_on > ?', today)
  }

  # Validations
  validates :name, :master_variant, :currency, presence: true
  validates :discount_percent, numericality: { greater_than_or_equal_to: 0, less_than_or_equal_to: 100 }
  validates :review_avg_rating, numericality: { in: 0..5 }
  validates :lowest_price, numericality: { greater_than_or_equal_to: 0 }, allow_nil: true
  validates :highest_price, numericality: { greater_than_or_equal_to: 0 }, allow_nil: true
  validates :thumbnail, content_type: ALLOWED_IMAGE_TYPES
  validates :images, content_type: ALLOWED_IMAGE_TYPES,
                     limit: { max: MAX_IMAGES, message: I18n.t('images.validate.max', max: MAX_IMAGES) }
end

# == Schema Information
#
# Table name: products
#
#  id                :uuid             not null, primary key
#  available_on      :date
#  currency          :string           default("PHP"), not null
#  discontinue_on    :date
#  discount_percent  :integer          default(0), not null
#  has_variant       :boolean          default(FALSE), not null
#  highest_price     :decimal(10, 2)
#  lowest_price      :decimal(10, 2)
#  name              :string           not null
#  order_must_login  :boolean          default(FALSE), not null
#  promotable        :boolean          default(TRUE), not null
#  review_avg_rating :decimal(1, 1)    default(0.0)
#  review_count      :integer          default(0)
#  created_at        :datetime         not null
#  updated_at        :datetime         not null
#
# Indexes
#
#  index_products_on_available_on    (available_on)
#  index_products_on_discontinue_on  (discontinue_on)
#  index_products_on_highest_price   (highest_price)
#  index_products_on_lowest_price    (lowest_price)
#  index_products_on_name            (name)
#

app/controllers/admin/products/images_controller.rb
# frozen_string_literal: true

class Admin::Products::ImagesController < Admin::BaseController
  load_and_authorize_resource :product
  authorize_resource class: false

  before_action :set_image, only: %i[update destroy position]

  # GET /admin/product/:product_id/images
  def index; end

  # PATCH/PUT /admin/product/:product_id/images/:id
  def update
    respond_to do |format|
      if @image.update(product_image_params[:image])
        format.turbo_stream
      else
        format.turbo_stream { render status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/product/:product_id/images/:id
  def destroy
    @image.purge
  end

  # POST /admin/product/:product_id/images/upload
  def upload
    respond_to do |format|
      if @product.update(images: product_image_params[:images])
        format.turbo_stream
      else
        format.turbo_stream { render status: :unprocessable_entity }
      end
    end
  end

  # PATCH /admin/product/:product_id/images/:id/position
  def position
    @image.update(sort_order_position: product_image_params[:position])

    head :ok
  end

  private

  def set_image
    @image = @product.images.find(params[:id])
  end

  def product_image_params
    params.require(:product_image).permit(:position, :image, images: [])
  end
end

app/controllers/admin/products/stocks_controller.rb
# frozen_string_literal: true

class Admin::Products::StocksController < Admin::BaseController
  load_and_authorize_resource :product
  authorize_resource class: false

  before_action :set_variant, only: %i[update modify]

  # GET /admin/product/:product_id/stocks
  def index
    @variants = @product.variants.sort_by_position.grouped_option_name
    @variants = @variants.master unless @product.has_variant
  end

  # PATCH/PUT /admin/product/:product_id/stocks/:id
  def update
    respond_to do |format|
      if @variant.update(variant_params)
        format.turbo_stream
      else
        format.turbo_stream { render status: :unprocessable_entity }
      end
    end
  end

  # PUT /admin/product/:product_id/stocks/:id/modify
  def modify
    count_on_hand = @variant.count_on_hand + variant_params[:modify_amount].to_i

    respond_to do |format|
      if @variant.update(count_on_hand:)
        format.turbo_stream
      else
        format.turbo_stream { render status: :unprocessable_entity }
      end
    end
  end

  private

  def set_variant
    @variant = @product.variants.find(params[:id])
  end

  def variant_params
    params.require(:variant).permit(:sku, :count_on_hand, :trackable, :backorderable, :modify_amount)
  end
end

app/controllers/products_controller.rb
# frozen_string_literal: true

class ProductsController < BaseController
  load_and_authorize_resource

  # GET /products
  def index
    @products = Product.base_on_date.sort_by_latest
    return if params[:category].blank?

    @products = @products.where(product_categories: { category: params[:category] }).joins(:product_categories)
  end

  # GET /products/:id
  def show
    @carousel = @product.images.sort_by_position
  end
end

app/helpers/products_helper.rb
# frozen_string_literal: true
# typed: true

module ProductsHelper
  extend T::Sig

  def currency_list
    Money::Currency.table.map do |cu|
      ["#{cu[1][:iso_code]} (#{cu[1][:symbol]})", cu[1][:iso_code]]
    end
  end

  sig { params(product: Product).returns(T.any(Integer, Float, BigDecimal)) }
  def pub_stock_num(product)
    return product.variants.not_master.sum(:count_on_hand) if product.has_variant

    T.must(product.master_variant).count_on_hand
  end

  sig { params(product: Product).returns(String) }
  def pub_variant_uuid(product)
    return '' if product.has_variant

    T.must(product.master_variant).id
  end
end

app/views/admin/products/_form.html.haml
= form_for(@product, url: path, html: {data: {controller: "admin--products--form"}, class: "w-full flex gap-5", method: method}) do |f|
  .flex.flex-col.gap-2.w-full
    - if @product.errors.present?
      = render ErrorMessageComponent.new(errors: @product.errors.full_messages, label: "validation")
    .field
      = f.label :name
      = f.text_field :name, required: true, placeholder: "e.g. Nike Shoe"
    .field
      = f.label :description
      = f.rich_text_area :description, placeholder: "Write here..."
    .field
      = f.label :categories
      = f.select :category_ids, Category.all.map {|cat| [cat.path.map {|p| p.name}.join(" -> "), cat.id]}, {}, {class: "h-[42px]", multiple: true, data: { "admin--products--form-target": "categoryInput" }}
    .flex.gap-3.items-center.pt-2
      = f.check_box :has_variant, class: "checkbox-primary", data: {action: "admin--products--form#hasVariantToogle"}
      = f.label :has_variant, "With variants"
    .field{class: ("hidden" unless f.object.has_variant), data: {"admin--products--form-target": "optionContainer"}}
      = f.label :options
      = f.select :option_ids, Option.pluck(:name, :id), {}, {class: "h-[42px]", multiple: true, data: { "admin--products--form-target": "optionInput" }}
    %h2.font-medium.text-lg.mt-1 SEO
    = f.fields_for :seo, @product.seo || Seo.new do |seo|
      .field
        = seo.label :meta_title
        = seo.text_field :meta_title
      .field
        = seo.label :meta_description
        = seo.text_area :meta_description
      .field
        = seo.label :meta_keywords
        = seo.text_field :meta_keywords
    .flex.justify-end
      = f.submit is_new ? "Create Product" : "Update Product", class: "mt-2 btn-primary w-fit cursor-pointer disabled:bg-gray-300 disabled:cursor-wait"
  .flex.flex-col.gap-2{class: "w-1/4 md:w-56 md:min-w-56"}
    .field
      = f.label :thumbnail
      = render "upload_thumbnail", form: f
    .field
      = f.label :available_on
      = f.date_field :available_on
    .field
      = f.label :discontinue_on
      = f.date_field :discontinue_on
    .field
      = f.label :currency
      = f.select :currency, currency_list, {selected: is_new ? MoneyRails.default_currency : @product.currency}, {required: true, disabled: true}
    .field
      = f.label :discount_percent, "Discount (%)"
      = f.number_field :discount_percent, required: true
    - if is_new
      = f.hidden_field :currency, value: MoneyRails.default_currency
    = f.fields_for :master_variant, @product.master_variant || Variant.new do |mv|
      .field
        = mv.label :price, "Master price"
        = mv.number_field :price, required: true, step: :any, placeholder: "0.00"
      .field
        = mv.label :cost, "Master cost"
        = mv.number_field :cost, step: :any, placeholder: "0.00"
      .field
        = mv.label :sku, "Master SKU"
        = mv.text_field :sku
      .space-y-1.mt-1{data: {controller: "admin--products--track"}}
        .flex.gap-2.items-center
          = mv.check_box :trackable, class: "checkbox-primary mt-0.5", data: {action: "admin--products--track#trackableToggle"}
          = mv.label :trackable, class: "cursor-pointer"
        .flex.gap-2.items-center{data: {"admin--products--track-target": "backorderable"}, class: ("hidden" if !mv.object.trackable)}
          = mv.check_box :backorderable, class: "checkbox-primary mt-0.5"
          = mv.label :backorderable, class: "cursor-pointer"
        - if is_new
          = mv.hidden_field :is_master, value: true

app/views/admin/products/_item.html.haml
%tr{id: dom_id(product)}
  %td.flex.gap-2.items-center
    - if product.thumbnail.attached?
      = image_tag(product.thumbnail.variant(:small), size: 100, class: "w-7 h-7 min-h-7 min-w-7 object-cover object-center rounded border")
    = product.name
  %td
    = render PriceRangeComponent.new lowest: product.lowest_price, highest: product.highest_price, discount: product.discount_percent
  %td
    = link_to product_path(product), target: "_blank", class: "text-lg text-gray-400 hover:text-primary transition-colors px-2 py-1 hover:bg-gray-100 rounded-md transition-all duration-200" do
      = icon("fa-solid", "arrow-right", class: "-rotate-45")
  %td
    .flex.gap-3.text-gray-400
      = link_to admin_product_path(product), class: "hover:text-primary transition-colors" do
        = icon("fa-solid", "eye")
      = button_to admin_product_path(product), class: "hover:text-red-600 transition-colors", method: :delete, form: {data: {turbo_confirm: 'Are you sure to delete this product?'}} do
        = icon("fa-solid", "trash")

app/views/admin/products/_tabs.html.haml
%ul.flex.text-sm.gap-1.text-center.font-medium.text-gray-500.border-b-2
  %li
    = render TabLinkComponent.new path: admin_product_path(@product) do
      = t("products.tabs.details")
  %li
    = render TabLinkComponent.new path: admin_product_images_path(@product) do
      = t("products.tabs.images")
  - if @product.has_variant 
    %li
      = render TabLinkComponent.new path: admin_product_variants_path(@product) do
        = t("products.tabs.variants")
  %li
    = render TabLinkComponent.new path: admin_product_stocks_path(@product) do 
      = t("products.tabs.stocks")
  %li
    = render TabLinkComponent.new path: product_path(@product), target: "_blank" do 
      .flex.gap-2.items-center
        = icon("fa-solid", "arrow-right", class: "-rotate-45")
        Visit

app/views/admin/products/_thumbnail_upload.html.haml
%label{for: "dropzone-file", class: "cursor-pointer rounded-md flex gap-3 items-center border-2 border-dashed border-gray-300 p-2 hover:border-primary transition-colors duration-100"}
  - if thumbnail.present?
    = image_tag(thumbnail, id: "thumbnail", class: "rounded max-h-28 border max-w-28 min-h-28 min-w-28 object-cover object-center")
  - else
    #thumbnail.min-w-28.min-h-28.border-2.flex.items-center.justify-center.rounded
      = icon("fa-regular", "image", class: "text-6xl text-gray-300")
  %span.text-sm.text-gray-500.dark:text-gray-400.text-center PNG, JPG, JPEG
  = form.file_field :thumbnail, id: "dropzone-file", accept: "image/png, image/jpg, image/jpeg", class: "hidden"

app/views/admin/products/_upload_thumbnail.html.haml
= form.file_field :thumbnail, id: "dropzone-file", class: "hidden", data: {action: "input->admin--products--form#thumbnail"}, accept: Product::ALLOWED_IMAGE_TYPES.join(", ")

%label{for: "dropzone-file", class: "bg-white cursor-pointer rounded-md flex gap-1 items-center border-2 border-dashed border-gray-400 p-2 hover:border-primary transition-colors duration-200 text-gray-500 hover:text-primary"}
  = image_tag form.object.thumbnail.attached? ? form.object.thumbnail.variant(:card) : "thumbnail.png", size: 320, id: "thumbnail", data: {"admin--products--form-target": "thumbnail"}, class: "rounded max-h-20 border max-w-20 min-h-20 min-w-20 object-cover object-center"
  .flex.justify-center.items-center.w-full.flex-col
    %p.font-medium Select Image
    %p.text-sm.uppercase
      = Product::ALLOWED_IMAGE_TYPES.join(", ").gsub("image/", "")

app/views/admin/products/destroy.turbo_stream.haml
= turbo_stream.prepend "notification-container" do
  = render NotificationComponent.new notif_type: "success", message: I18n.t('products.destroyed')
= turbo_stream.remove dom_id(@product)

app/views/admin/products/index.html.haml
.margin-max-screen.py-7
  .flex.flex-col.gap-6
    .flex.gap-5.justify-between.items-start
      %h2.font-semibold.text-xl
        = t("products.title")
      = button_to new_admin_product_path, class: "btn-primary flex gap-2.5 items-center", method: :get do
        = t("products.new")
        = icon("fa-solid", "plus")
    .grid.gap-3
      %table
        %thead
          %tr
            %th= t("products.table.thead.name")
            %th= t("products.table.thead.price")
            %th= t("products.table.thead.visit")
            %th= t("products.table.thead.actions")
        %tbody
          - if @products.present?
            - @products.each do |product|
              = render "item", product:
          - else
            %tr
              %td{colspan: 4}= t("products.no_list_found")
      - if @pagy.pages > 1          
        .flex.gap-3.items-center.w-full.justify-between
          != pagy_nav(@pagy)
          != pagy_info(@pagy)

app/views/admin/products/new.html.haml
.margin-max-screen.py-7.space-y-3
  %h1.text-2xl.font-semibold= t('products.create')
  = render 'form', path: admin_products_path, method: :post, is_new: true

app/views/admin/products/show.html.haml
.margin-max-screen.py-7.flex.flex-col.gap-5
  = render "tabs"
  = render "form", path: admin_product_path(@product), method: :put, is_new: false

app/views/admin/products/stocks.html.haml
.margin-max-screen.h-full.py-8.flex.flex-col.gap-5
  = render "tabs"

app/views/admin/products/variants.html.haml
.margin-max-screen.h-full.py-8.flex.flex-col.gap-5
  = render "tabs"
  .flex.flex-col.gap-6
    .flex.gap-5.justify-between.items-center
      %div
      = button_to new_admin_product_path, class: "btn-plain flex gap-2.5 items-center", method: :get do
        New Variant
        = icon("fa-solid", "plus")
    %table
      %thead
        %tr
          %th Name
          %th Price
          %th Actions
      %tbody
        - if @variants.present?
          - @variants.each do |variant|
            %tr
              %td
              %td
              %td
        - else
          %tr
            %td
              No variants found
            %td
            %td